name: TrainShop CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run lint
      - run: npm test


  docker-test:
    runs-on: ubuntu-latest
    needs: test-api

    env:
    CI: true
    
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t trainshop-api ./api

      - name: Show Docker images
        run: docker images

      - name: Run container
        run: docker run -d -p 3000:3000 --name api trainshop-api

      - name: Wait for API ready
        run: |
          for i in {1..15}; do
            curl -f http://localhost:3000/health && exit 0
            echo "waiting API..."
            sleep 2
          done
          exit 1

      # ===== TESTS API =====
      - name: Test /health
        run: curl -f http://localhost:3000/health

      - name: Test /ready
        run: curl -f http://localhost:3000/ready

      - name: Test /products
        run: curl -f http://localhost:3000/products

      - name: Test /metrics
        run: curl -f http://localhost:3000/metrics

      # ===== DEBUG =====
      - name: Show containers
        if: failure()
        run: docker ps -a

      - name: Show logs
        if: failure()
        run: docker logs api

      - name: Debug health
        if: failure()
        run: curl http://localhost:3000/health || true

      - name: Debug ready
        if: failure()
        run: curl http://localhost:3000/ready || true

      - name: Debug metrics
        if: failure()
        run: curl http://localhost:3000/metrics || true

      # ===== CLEAN =====
      - name: Cleanup
        if: always()
        run: docker rm -f api