name: TrainShop CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm test


  docker-build:
    runs-on: ubuntu-latest
    needs: test-api

    steps:
      - uses: actions/checkout@v4

      # build API
      - name: Build API image
        run: docker build -t trainshop-api ./api

      # build frontend
      - name: Build Frontend image
        run: docker build -t trainshop-frontend ./frontend

      # run API container
      - name: Run API container
        run: docker run -d -p 3000:3000 --name api trainshop-api

      # wait API
      - name: Wait API startup
        run: sleep 5

      # test health
      - name: Test /health
        run: curl http://localhost:3000/health

      # cleanup
      - name: Stop container
        if: always()
        run: docker rm -f api